name: App Update Check

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.0.0
        with:
          always-auth: false
          node-version: 16.x
          cache: npm

      - run: npm install
      - run: npm run start --if-present

      - name: Commit Version
        run: |
          git config --global user.name 'boomboompower'
          git config --global user.email '12974350+boomboompower@users.noreply.github.com'
          git add docs/settings.js
          git commit -m "Update ${{ steps.version.outputs.content }}"
          git push
