name: App Update Check

on:
  workflow_dispatch:
    inputs:
      message:
        description: The commit message to use
        required: false

jobs:
  check:
    if: github.repository == 'boomboompower/twitch-experiments' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          always-auth: false
          node-version: 16.x
          cache: npm

      - name: Restore Cached Versions
        id: cache-version-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            docs/time.txt
            docs/version.txt
          key: ${{ runner.os }}-versions-${{ hashFiles('**/settings.js', '**/production.js') }}

      - run: npm install
      - run: npm run start --if-present
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - name: Read Version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./docs/version.txt

      - name: Read Release Time
        id: time
        uses: juliangruber/read-file-action@v1
        with:
          path: ./docs/time.txt

      - name: Commit Version
        shell: bash
        run: |
          git config --global user.name 'github-bot'
          git config --global user.email '6031226+github-bot@users.noreply.github.com'
          git add docs/settings.js
          git add docs/production.js
          if [ "${{ github.event.inputs.message }}" == "" ]; then
            git commit -m "${{ steps.time.outputs.content }} - New Build ${{ steps.version.outputs.content }}"
          else
            git commit -m "${{ github.event.inputs.message }}"
          fi
          git push
        continue-on-error: true

      - name: Save Versions to Cache
        if: success() || failure()
        id: cache-versions-save
        uses: actions/cache/save@v3
        with:
          path: |
            docs/time.txt
            docs/version.txt
          key: ${{ runner.os }}-versions-${{ hashFiles('**/settings.js', '**/production.js') }}

      - name: Done
        run: |
          echo Goodbye!
