name: Deploy website
on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'boomboompower/twitch-experiments'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          always-auth: false
          node-version: 16.x
          cache: npm
      
      - run: npm install
      - run: npm run start --if-present
      
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./docs
